"""empty message

Revision ID: 761ae1ef91e6
Revises: 
Create Date: 2025-11-24 17:05:58.970998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761ae1ef91e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
